services:
  postgres:
    container_name: sqlservice
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sqlservice
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d sqlservice"]
      interval: 10s
      timeout: 5s
      retries: 5


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: sqlservice_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: sqlservice_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  # Тестовый контейнер для задач (можно добавить несколько)
  postgres-test-1:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - ./sql/init_task1.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data: